// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdem5UsBUULQ-hFditk3Wb8YXcE8jmcMk',
    appId: '1:868652296203:web:a2470abfcbc1f6fc6cbf0e',
    messagingSenderId: '868652296203',
    projectId: 'practice-c374e',
    authDomain: 'practice-c374e.firebaseapp.com',
    storageBucket: 'practice-c374e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDBKkircSvVAPESMa55HWNwu3rgpPifo',
    appId: '1:868652296203:android:5c6c4f7c5854ed686cbf0e',
    messagingSenderId: '868652296203',
    projectId: 'practice-c374e',
    storageBucket: 'practice-c374e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwFFb3er9aaIUX9ItLjBwRRJCkLBmkP4',
    appId: '1:868652296203:ios:104b4109403211dd6cbf0e',
    messagingSenderId: '868652296203',
    projectId: 'practice-c374e',
    storageBucket: 'practice-c374e.appspot.com',
    iosBundleId: 'com.example.codecarnival',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlwFFb3er9aaIUX9ItLjBwRRJCkLBmkP4',
    appId: '1:868652296203:ios:9296e7a64f7262a26cbf0e',
    messagingSenderId: '868652296203',
    projectId: 'practice-c374e',
    storageBucket: 'practice-c374e.appspot.com',
    iosBundleId: 'com.example.codecarnival.RunnerTests',
  );
}
